include: package:flutter_lints/flutter.yaml
analyzer:
    errors:
        prefer_conditional_assignment: ignore
        prefer_const_constructors: ignore
        prefer_interpolation_to_compose_strings: ignore
