name: scout_link
description: 'A new Flutter project.'
publish_to: 'none'
version: 0.1.0

environment:
    sdk: ^3.5.0

dependencies:
    flutter:
        sdk: flutter
    easy_localization: ^3.0.7

dev_dependencies:
    flutter_test:
        sdk: flutter
    flutter_lints: ^4.0.0

flutter:
    uses-material-design: true
    assets:
        - assets/translations/
