name: scout_link
description: 'A new Flutter project.'
publish_to: 'none'
version: 0.1.0

environment:
    sdk: ^3.5.0

dependencies:
    flutter:
        sdk: flutter
    flutter_displaymode: ^0.6.0
    device_preview: ^1.2.0
    shared_preferences: ^2.3.2
    get: ^4.6.6
    logger: ^2.4.0
    sliding_clipped_nav_bar: ^3.1.1

dev_dependencies:
    flutter_test:
        sdk: flutter
    flutter_lints: ^4.0.0

flutter:
    uses-material-design: true
    fonts:
        - family: Avenir
          fonts:
              - asset: assets/fonts/avenir/avenirLTStd-Book.otf
                weight: 300
              - asset: assets/fonts/avenir/avenirLTStd-Black.otf
                weight: 900
              - asset: assets/fonts/avenir/avenirLTStd-Light.otf
                weight: 100
              - asset: assets/fonts/avenir/avenirLTStd-Medium.otf
                style: normal
                weight: 500
              - asset: assets/fonts/avenir/avenirLTStd-Heavy.otf
                weight: 800
