name: scout_link
description: 'A new Flutter project.'
publish_to: 'none'
version: 0.1.0

environment:
    sdk: ^3.5.0

dependencies:
    flutter:
        sdk: flutter
    flutter_displaymode: ^0.6.0
    device_preview: ^1.2.0
    shared_preferences: ^2.3.2
    get: ^4.6.6
    logger: ^2.4.0
    sliding_clipped_nav_bar: ^3.1.1
    appwrite: ^13.0.0

dev_dependencies:
    flutter_test:
        sdk: flutter
    flutter_lints: ^4.0.0

flutter:
    uses-material-design: true
